# Custom zsh config using zinit
# Author: Alexandre Guerville <alexandre@guerville.dev>

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

if [ ! -d "$ZINIT_HOME" ]; then
    mkdir -p "$ZINIT_HOME"
    git clone git@github.com:zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"

## Zinit Setting
# Must Load OMZ Git library
# zi snippet OMZL::git.zsh

# Load Git plugin from OMZ
zi snippet OMZP::git
zi snippet OMZP::sudo
# zi snippet OMZP::archlinux
# zi snippet OMZP::command-not-found
zi cdclear -q # <- forget completions provided up to this moment

setopt promptsubst

zi snippet OMZL::clipboard.zsh
# zi snippet OMZL::termsupport.zsh

# Custom plugins
zi light zsh-users/zsh-syntax-highlighting
zi light zsh-users/zsh-completions
zi light zsh-users/zsh-autosuggestions
zi light Aloxaf/fzf-tab
zi light agnoster/agnoster-zsh-theme

# Keybinds
bindkey -e
bindkey "^k" history-search-backward
bindkey "^l" history-search-forward

autoload -U compinit && compinit
zi cdreplay -q

HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Commpletion Options
zstyle ':completion:*' matcher-list 'm:{a-z}={a-zA-Z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no

# Alias
alias ls='ls --color'
alias grep='rg'

# Fuzzy Finder
eval "$(fzf --zsh)"
